USE [master]
GO

/****** Object:  Database [TouristAgency]    Script Date: 14.06.2022 9:30:58 ******/
CREATE DATABASE [TouristAgency]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TouristAgency', FILENAME = N'E:\TouristAgency.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TouristAgency_log', FILENAME = N'E:\TouristAgency_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TouristAgency].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TouristAgency] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TouristAgency] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TouristAgency] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TouristAgency] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TouristAgency] SET ARITHABORT OFF 
GO

ALTER DATABASE [TouristAgency] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TouristAgency] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TouristAgency] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TouristAgency] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TouristAgency] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TouristAgency] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TouristAgency] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TouristAgency] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TouristAgency] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TouristAgency] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TouristAgency] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TouristAgency] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TouristAgency] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TouristAgency] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TouristAgency] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TouristAgency] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TouristAgency] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TouristAgency] SET RECOVERY FULL 
GO

ALTER DATABASE [TouristAgency] SET  MULTI_USER 
GO

ALTER DATABASE [TouristAgency] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TouristAgency] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TouristAgency] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TouristAgency] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TouristAgency] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TouristAgency] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TouristAgency] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TouristAgency] SET  READ_WRITE 
GO


